---
title: "Анализ данных сетевого трафика при помощи библиотеки Arrow"
format: 
  md:
    output-file: README.md
---

## Цель

1. Изучить возможности технологии [Apache Arrow](https://arrow.apache.org/) для обработки и анализ больших данных
2. Получить навыки применения Arrow совместно с языком программирования R
3. Получить навыки анализа `метаинфомации о сетевом трафике`
4. Получить навыки применения облачных технологий хранения, подготовки и анализа данных: [Yandex Object Storage](https://yandex.cloud/ru/docs/storage/), [Rstudio Server](https://posit.co/products/open-source/rstudio-server/).

## ️Исходные данные

1.  R 4.4.1
2.  RStudio 2024.04.2+764
3.  Yandex Cloud

## ️Общий план выполнения

Используя язык программирования `R`, библиотеку `arrow` и облачную `IDE Rstudio Server`, развернутую в `Yandex Cloud`, выполнить задания и составить отчет.

## Содержание ЛР

### Получение данных

1. **Установка пакета**

```{R}
library(arrow)
library(dplyr)
```

2. **Загрузка данных**

```{R}
data <- read_parquet("./data/tm_data.pqt")
```

3. **Проверка получения данных**

```{R}
glimpse(data)
```

### Задание 1: Найдите утечку данных из Вашей сети

Важнейшие документы с результатами нашей исследовательской деятельности в области создания вакцин скачиваются в виде больших заархивированных дампов. Один из хостов в нашей сети используется для пересылки этой информации – он пересылает гораздо больше информации на внешние ресурсы в Интернете, чем остальные компьютеры нашей сети. Определите его IP-адрес

```{R}
data %>% 
  filter(grepl("^1[2|3|4]\\..+", src) & !grepl("^1[2|3|4]\\..+", dst)) %>%
  group_by(src) %>%
  summarise(traffic = sum(bytes)) %>%
  arrange(desc(traffic)) %>%
  head(1) %>%
  select(src) %>%
  knitr::kable()
```
    
### Задание 2: Найдите утечку данных 2

Другой атакующий установил автоматическую задачу в системном планировщике cron для экспорта содержимого внутренней wiki системы. Эта система генерирует большое количество трафика в нерабочие часы, больше чем остальные хосты. Определите IP этой системы. Известно, что ее IP адрес отличается от нарушителя из предыдущей задачи.

```{R}
data %>%
  filter(grepl("^1[2|3|4]\\..+", src) & !grepl("^1[2|3|4]\\..+", dst)) %>%
  mutate(timestamp = as.POSIXct(timestamp / 1000, origin = "1970-01-01", tz = "UTC")) %>%
  mutate(hour = format(timestamp, "%H")) %>%
  group_by(hour) %>%
  summarise(sd = sd(bytes)) %>%
  arrange(desc(sd)) %>%
  head() %>%
  select(hour) %>%
  knitr::kable()
```

```{R}
data %>%
  filter(grepl("^1[2|3|4]\\..+", src) & !grepl("^1[2|3|4]\\..+", dst)) %>%
  mutate(timestamp = as.POSIXct(timestamp / 1000, origin = "1970-01-01", tz = "UTC")) %>%
  mutate(hour = format(timestamp, "%H")) %>%
  filter(hour == "07") %>%
  group_by(src) %>%
  summarise(traffic = sum(bytes)) %>%
  arrange(desc(traffic)) %>%
  head(1) %>%
  select(src) %>%
  knitr::kable() 
```

### Задание 3: Найдите утечку данных 3

Еще один нарушитель собирает содержимое электронной почты и отправляет в Интернет используя порт, который обычно используется для другого типа трафика. Атакующий пересылает большое количество информации используя этот порт, которое нехарактерно для других хостов, использующих этот номер порта. Определите IP этой системы. Известно, что ее IP адрес отличается от нарушителей из предыдущих задач.

```{R}
data %>%
  filter(grepl("^1[2|3|4]\\..+", src) & !grepl("^1[2|3|4]\\..+", dst)) %>%
  group_by(port) %>%
  summarise(sd = sd(bytes),
            min = min(bytes),
            max = max(bytes),
            med = median(bytes),
            men = mean(bytes),
            x = men - med) %>%
  arrange(desc(sd)) %>%
  knitr::kable()
```

```{R}
data %>%
  filter(grepl("^1[2|3|4]\\..+", src) & !grepl("^1[2|3|4]\\..+", dst) & port==124) %>%
  group_by(src) %>%
  summarise(traffic = sum(bytes)) %>%
  arrange(desc(traffic)) %>%
  head(1) %>%
  select(src) %>%
  knitr::kable()
```
    
## ️Оценка результата

Был проведён анализ сетевого трафика при помощи библиотеки `arrow`

## ️Вывод

В результате выполнения работы были:

+ изучены возможности технологии [Apache Arrow](https://arrow.apache.org/) для обработки и анализ больших данных
+ Получены навыки применения `arrow` совместно с языком программирования `R`
+ получены навыки анализа `метаинфомации о сетевом трафике`